services:
  - type: web
    name: emma-web-app
    env: node
    buildCommand: npm install --production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false  # Set manually in Render dashboard
